### ISSUE TITLE
Probleme bei Make all, Make Specific und Make Pool

### ISSUE THREAD

**Issue by sputeanus** [TUD-RST/examgenerator#19]
Make all, Make Specific und Make pool scheinen nur einmal ausgeführt werden zu können. Beim zweiten Mal erscheint eine Fehlermeldung (siehe unten.).  Es wirkt so als würde irgendwie intern schon was geöffnet zu sein. (Wobei problem_1 eh schon vorhanden sein müsste.... mysteriös).
Auch ein Neustart des Systems bringt nix. Fehlermeldung bleibt die Gleiche.

Sonnige Grüße
Simon

`C:\Users\Puteanus\Nextcloud\17Semester\ExamGenerator\examgenerator\examples\example1>exam_generator -ma
Traceback (most recent call last):
  File "C:\Users\Puteanus\AppData\Local\Programs\Python\Python311\Scripts\exam_generator-script.py", line 33, in <module>
    sys.exit(load_entry_point('exam-generator', 'console_scripts', 'exam_generator')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\puteanus\nextcloud\17semester\examgenerator\examgenerator\src\exam_generator\main.py", line 301, in main
    exam_generator(args)
  File "c:\users\puteanus\nextcloud\17semester\examgenerator\examgenerator\src\exam_generator\main.py", line 45, in exam_generator
    make_specific(args.make_all, args.make_pool, args.make_specific, root_directory)
  File "c:\users\puteanus\nextcloud\17semester\examgenerator\examgenerator\src\exam_generator\funcs.py", line 1001, in make_specific
    filenames_problems = preview_parameterization(root_directory, filenames_problems)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\puteanus\nextcloud\17semester\examgenerator\examgenerator\src\exam_generator\funcs.py", line 1110, in preview_parameterization
    os.rename(name, new_name)
FileExistsError: [WinError 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: 'problem_1.tex' -> 'MC_easy_problem_1.tex'`

**Comment by sputeanus** [comment]
![grafik](https://user-images.githubusercontent.com/117989161/203977060-a344e826-4390-4eb3-8a57-09e634e3c333.png)
